### ISSUE TITLE
"No mqtt_topic specified for an entry in topics list" - using example config

### ISSUE THREAD

**Issue by ashtonian** [mtreinish/mqtt_statsd#1]
Hey I know this is old but its nice :) wrapping it in docker image and I'm getting the following: 
config.yaml:

```
statsd:
  hostname: datadog-agent.tools
  # port is optional, the default is shown
  port: 8125
  # prefix is optional, the default is shown
  prefix: mosquitto.stats
mqtt:
  hostname: mqtt host
  # port is optional, the default is shown
  port: 1883
  # keepalive is optional, the default is shown
  keepalive: 60
  # username is optional, there is no default
  username: userme
  # password is optional, there is no default. If username isn't set this
  # is ignored
  password: i'm a password
  # qos is optional, the default is shown
  qos: 0
  # websocket is optional, it defaults to False
  websocket: True
topics:
  # You can specify as many topics as you want, and mqtt_statsd will
  # listen to all of them
  - $SYS/broker/messages/publish/sent:
    statsd_topic: publish_messages_sent
    # statsd_type is optional, the default is shown. Valid options are
    # gague, counter, and timer
    statsd_type: gauge

  - $SYS/broker/clients/connected:
    statsd_topic: connected_clients
```

```
6/9/2021 7:40:50 PM/usr/local/lib/python3.9/site-packages/mqtt_statsd/daemon.py:73: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
6/9/2021 7:40:50 PM  conf = yaml.load(conf_file.read())
6/9/2021 7:40:50 PMNo mqtt_topic specified for an entry in topics list
```
